"""create suggestions and review_decisions

Revision ID: 6f7fbb9c3c59
Revises: 205804495510
Create Date: 2026-08-21 14:53:19.504436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7fbb9c3c59'
down_revision: Union[str, Sequence[str], None] = '205804495510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'image_id', name='uq_suggestions_post_image')
    )
    op.create_index(op.f('ix_suggestions_image_id'), 'suggestions', ['image_id'], unique=False)
    op.create_index(op.f('ix_suggestions_post_id'), 'suggestions', ['post_id'], unique=False)
    op.create_index(op.f('ix_suggestions_status'), 'suggestions', ['status'], unique=False)
    op.create_table('review_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decisions_created_at'), 'review_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_decisions_suggestion_id'), 'review_decisions', ['suggestion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_decisions_suggestion_id'), table_name='review_decisions')
    op.drop_index(op.f('ix_review_decisions_created_at'), table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_suggestions_status'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_post_id'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_image_id'), table_name='suggestions')
    op.drop_table('suggestions')
    # ### end Alembic commands ###
